### ISSUE TITLE
Unpack canvas on Power App release 3.21111.22

### ISSUE THREAD

**Issue by maxdomico** [microsoft/PowerApps-Language-Tooling#319]
We have an issue to unpack canvas which the Power Apps release is 3.21111.22. 
`Sorry, the app encountered a non recoverable error and will need to terminate. The exception details have been captured and will be forwarded to the development team, if telemetry has been enabled`

if we roll back to the previous version 3.21103.27, it is working.

**Comment by PandaLord** [comment]
Same Issue. And you cannot change to the previous version once you save your canvas app in the latest environment.

**Comment by maxdomico** [comment]
> Same Issue. And you cannot change to the previous version once you save your canvas app in the latest environment.

But we can't change it back, so sadly we can't unpack the .msapp to do anything.

**Comment by PandaLord** [comment]
we found a workaround for this. You can add a parameter to the URL after you click the "Edit" of the specific app.
Add this after the app url: &studio-version=v3.21103.27.202362840

**Comment by maxdomico** [comment]
> 3.21103.27.202362840

Thanks for your information. Unlucky for me :(, it forces me to open with the new version.
![image](https://user-images.githubusercontent.com/34846356/141978105-ebe1a337-46b8-4e00-9c16-93fe90b21360.png)

**Comment by PandaLord** [comment]
Don't worry. it is common to have this notification. You can restore to previous version first or simply do it one more time, it will allow you to open directly. Once you have a previous version, you can save it and download a proper one msapp.

**Comment by maxdomico** [comment]
> Don't worry. it is common to have this notification. You can restore to previous version first or simply do it one more time, it will allow you to open directly. Once you have a previous version, you can save it and download a proper one msapp.

I got your point, but if we roll back to the previous version. the recent development is gone. How do I get them back?

**Comment by Kahltor** [comment]
Same issue for us.
![image](https://user-images.githubusercontent.com/2686851/142182106-eb3d6129-1ae2-4faf-8bf5-1e82b2e85738.png)

**Comment by maxdomico** [comment]
> Same issue for us. ![image](https://user-images.githubusercontent.com/2686851/142182106-eb3d6129-1ae2-4faf-8bf5-1e82b2e85738.png)

For your case, assume "groupCotainer" is a group, you should check whether the group exists and regroup a different name? The error message showed the key is duplicated. Hope this can help you.

**Comment by Kahltor** [comment]
> > Same issue for us. ![image](https://user-images.githubusercontent.com/2686851/142182106-eb3d6129-1ae2-4faf-8bf5-1e82b2e85738.png)
> 
> Kahltor, for your case, assume "groupCotainer" is a group, you should check whether the group exists and regroup a different name? The error message showed the key is duplicated. Hope this can help you.

This is an internal error from tooling. In our App there is neither group nor container with name "groupContainer". GroupContainer is an internal name for a layout container control:
![image](https://user-images.githubusercontent.com/2686851/142280767-69e6e534-c270-4f2f-a758-663596c3f642.png)

BTW rollback to v3.21102.25 worked as expected (with loss of the latest changes) and we were able to unpack and pack our app.

**Comment by lesaltzm** [comment]
This bug was resolved by this fix: https://github.com/microsoft/PowerApps-Language-Tooling/commit/9d4d107765e879b31d6ffcacc936d4b1947ceec1, and that should be picked up by the next version of PAC, whenever that releases.

**Comment by hankanman** [comment]
@lesaltzm not resolved, please see: https://github.com/microsoft/powerplatform-vscode/issues/120#issuecomment-972810626

**Comment by wojtasey** [comment]
> This bug was resolved by this fix: [9d4d107](https://github.com/microsoft/PowerApps-Language-Tooling/commit/9d4d107765e879b31d6ffcacc936d4b1947ceec1), and that should be picked up by the next version of PAC, whenever that releases.

Do we have any ETA for this release? It's a blocker for my team.

**Comment by wjhepworth-tt** [comment]
> > This bug was resolved by this fix: [9d4d107](https://github.com/microsoft/PowerApps-Language-Tooling/commit/9d4d107765e879b31d6ffcacc936d4b1947ceec1), and that should be picked up by the next version of PAC, whenever that releases.
> 
> Do we have any ETA for this release? It's a blocker for my team.

Yes, this one is major.  When previous issues like this were encountered there were workarounds; however, no acceptable workarounds exist this time.

**Comment by PandaLord** [comment]
ok, everyone. We found the root cause about this. Just like @Kahltor mentioned, it's about the groupContainer control. So i have such workarounds for you:
1. if you can remove all the container control in your app( i mean with small efforts), you can simply remove all container controls and you will see you can unpack the msapp even in the latest studio version.
2. if you cannot use the approach 1, here is another option. First you need duplicate your major canvas app, then revert its version to  3.21103.27. i know it may occur a popup to let u update to latest, but keep restore it to the specified version until you get a stable 3.21103.27 studio version
3. you need to Ctrl C & V the changes you have in the latest studio version to the previous studio version app. This is a one-time task.
4. After that, you need make sure every time you save with the 3.21103.27 studio version. Then everything will be the same just like before.
Hopefully this will be helpful to you guys.

**Comment by wjhepworth-tt** [comment]
Thank you for the info, PandaLord.  Unfortunately, our app is really built upon containers.  Removing them is impossible at this juncture.  Based on the previous comments in this thread it seems that this is hopefully just a schema issue that can be fixed on the next update.   Fingers crossed.


-Bill

**Comment by maxdomico** [comment]
Guys,

I find a solution to use pasopa. command to unpack/pack .msapp file. **[Verified]**

1. Install .NET Core 3.1.x (x64).
2. Clone the repo at https://github.com/microsoft/PowerApps-Language-Tooling
3. Run build.cmd in the root directory.
4. You can find PASopa.exe and needed dependencies in the bin\Debug\PASopa directory.
5. To unpack a .msapp file: pac canvas unpack --msapp FromApp.msapp --sources ToSourceFolder
6. To pack a .msapp file: pac canvas pack --msapp ToApp.msapp --sources FromSourceFolder

**Comment by jjaramillo** [comment]
> Guys,
> 
> I find a solution to use pasopa. command to unpack/pack .msapp file. **[Verified by myself]**
> 
> 1. Install .NET Core 3.1.x (x64).
> 2. Clone the repo at https://github.com/microsoft/PowerApps-Language-Tooling
> 3. Run build.cmd in the root directory.
> 4. You can find PASopa.exe and needed dependencies in the bin\Debug\PASopa directory.
> 5. To unpack a .msapp file: pac canvas unpack --msapp FromApp.msapp --sources ToSourceFolder
> 6. To pack a .msapp file: pac canvas pack --msapp ToApp.msapp --sources FromSourceFolder

I've tried this but when I pack the app into the solution and import it to the environment I get the following message:
![image](https://user-images.githubusercontent.com/962447/144085310-c5c99a1e-5b79-414d-b7c7-96f4fdeff0e2.png)

**Comment by devkeydet** [comment]
pac 1.10.4 is on nuget now:
https://www.nuget.org/packages/Microsoft.PowerApps.CLI/1.10.4
From the release notes:
![image](https://user-images.githubusercontent.com/4499296/145565631-cb6e88db-201a-498a-ab2f-e0388b4a3b81.png)

**Comment by anskanth** [comment]
Is there any resolution for this? Unfortunately our app has number of container controls and its no way possible for us to remove them. And also it is not possible to change the version of the app as well as we have so much of functionality built in last couple of days.. 

I just need to unpack the file to compare the changes with previous version..  I tried @jjaramillo suggestion to use PASopa, that didnt worked either.. 

any thoughts/solutions?

**Comment by hankanman** [comment]
> 

Update to PAC CLIE 1.10.4 resolves this https://www.nuget.org/packages/Microsoft.PowerApps.CLI/1.10.4

**Comment by anskanth** [comment]
@hankanman i tried that already .. no luck..  :(
<img width="662" alt="image" src="https://user-images.githubusercontent.com/20016296/146530418-afa65c16-70b9-4ffd-9c43-cb66a992ccfe.png">

**Comment by hankanman** [comment]
@anskanth I did have this on one compile, but there was an issue with the app itself, try re-exporting the app and unpacking again first. I don't mind taking a look for you if you share the .msapp file

**Comment by PandaLord** [comment]
@anskanth you can try "pac use latest" first.

**Comment by NimbiMac** [comment]
Anyone been able to find which files / directory / properties are causing the following error?
_PA3001: Internal error. An item with the same key has already been added. Key: groupContainer_

`Have used pasopa -unpack [msapp] [directory for unpacked files]`

Have used another tool to be able to search and edit files before being unpacked by this source code tool. But unable to spot what the issue could be. Have searched the folders for groupContainer and looked at all references. there is no Key property in there so not sure how to continue hunting for the error. 

I can tell this is to do with the app I am trying to unpack as I tested with a very small and fresh app which worked fine. 

So, wanting some pointers to help me continue hunting this and what part of the app files are causing it.
